---
kind: pipeline
type: docker
name: PR checks

steps:
  - name: build
    image: node:14.11-alpine
    commands:
      - npm ci
  - name: lint
    image: node:14.11-alpine
    commands:
      - npm run lint
  - name: test
    image: zenika/alpine-chrome:89-with-node-14
    commands:
      - npm test:ci
#  - name: e2e
#    image: node:14.11-alpine
#    commands:
#      - npm run e2e

trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: Latest master pipeline
steps:
  - name: build & publish docker image to ECR
    image: plugins/ecr
    settings:
      mirror: https://proxy.docker.all.berlingskemedia.net
      access_key:
        from_secret: aws_access_key_testing
      secret_key:
        from_secret: aws_access_key_secret_testing
      region: eu-west-1
      repo: cust-testing-newsletter-ecr/notification-dashboard
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - ${DRONE_BUILD_NUMBER}-${CI_COMMIT_SHA}
        - ${CI_COMMIT_SHA}
  - name: deploy to testing
    image: pelotech/drone-ecs:1.0.7
    environment:
      GOOGLE_OAUTH_CLIENT_ID:
        from_secret: google_oauth_client_id_testing
      GOOGLE_OAUTH_CLIENT_SECRET:
        from_secret: google_oauth_client_secret_testing
      GIGYA_APP_KEY:
        from_secret: gigya_app_key_testing
      GIGYA_USER_KEY:
        from_secret: gigya_user_key_testing
      GIGYA_SECRET:
        from_secret: gigya_secret_testing
      ACCESS_KEY_ID:
        from_secret: dynamo_db_access_key_testing
      SECRET_ACCESS_KEY:
        from_secret: dynamo_db_access_key_secret_testing
    settings:
      access_key:
        from_secret: aws_access_key_testing
      secret_key:
        from_secret: aws_access_key_secret_testing
      cluster: cust-testing-newsletter
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-testing-newsletter-ecr/notification-dashboard
      container_name: cust-testing-newsletter-notification-dashboard-container
      family: cust-testing-newsletter-notification-dashboard
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-testing-newsletter
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=newsletter-notification-dashboard
      memory: 512
      port_mappings:
        - 3000 3000
      region: eu-west-1
      secret_environment_variables:
        - GOOGLE_OAUTH_CLIENT_ID
        - GOOGLE_OAUTH_CLIENT_SECRET
        - GIGYA_APP_KEY
        - GIGYA_USER_KEY
        - GIGYA_SECRET
        - ACCESS_KEY_ID
        - SECRET_ACCESS_KEY
      service: cust-testing-newsletter-notification-dashboard
      service_network_security_groups:
        - sg-04532122919e3abd0
        - sg-0a7eb053aa45ba0c1
      service_network_subnets:
        - subnet-061a8876f7f68ea21
        - subnet-0ace4f6a68677187c
        - subnet-01633ca14c693e302
      tag: ${DRONE_BUILD_NUMBER}-${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-testing-newsletter-notification-dashboard-exec
      task_memory: 512
      task_network_mode: awsvpc
trigger:
  event:
    - push
  branch:
    - master
    - BMD-7097

---
kind: pipeline
type: docker
name: deploy pipeline
clone:
  disable: true

steps:
  - name: deploy to production
    image: pelotech/drone-ecs:1.0.7
    environment:
      GOOGLE_OAUTH_CLIENT_ID:
        from_secret: google_oauth_client_id_production
      GOOGLE_OAUTH_CLIENT_SECRET:
        from_secret: google_oauth_client_secret_production
      GIGYA_APP_KEY:
        from_secret: gigya_app_key_production
      GIGYA_USER_KEY:
        from_secret: gigya_user_key_production
      GIGYA_SECRET:
        from_secret: gigya_secret_production
      ACCESS_KEY_ID:
        from_secret: dynamo_db_access_key_production
      SECRET_ACCESS_KEY:
        from_secret: dynamo_db_access_key_secret_production
    settings:
    access_key:
      from_secret: aws_access_key_production
    secret_key:
      from_secret: aws_access_key_secret_production
    cluster: cust-production-newsletter
    compatibilities: FARGATE
    deployment_configuration: 100 200
    desired_count: 1
    docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-production-newsletter-ecr/notification-dashboard
    container_name: cust-production-newsletter-notification-dashboard-container
    family: cust-production-newsletter-notification-dashboard
    log_driver: awslogs
    log_options:
      - awslogs-group=cust-production-newsletter
      - awslogs-region=eu-west-1
      - awslogs-stream-prefix=newsletter-notification-dashboard
    memory: 512
    port_mappings:
      - 3000 3000
    region: eu-west-1
    secret_environment_variables:
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - GIGYA_APP_KEY
      - GIGYA_USER_KEY
      - GIGYA_SECRET
      - ACCESS_KEY_ID
      - SECRET_ACCESS_KEY
    service: cust-production-newsletter-notification-dashboard
    service_network_security_groups:
      - sg-04532122919e3abd0
      - sg-0a7eb053aa45ba0c1
    service_network_subnets:
      - subnet-061a8876f7f68ea21
      - subnet-0ace4f6a68677187c
      - subnet-01633ca14c693e302
    tag: ${DRONE_BUILD_PARENT}-${CI_COMMIT_SHA}
    task_cpu: 256
    task_execution_role_arn: arn:aws:iam::815296035528:role/cust-production-newsletter-notification-dashboard-exec
    task_memory: 512
    task_network_mode: awsvpc
    when:
      event:
        - promote
      target:
        - production
trigger:
  event:
    - promote

---
kind: secret
name: aws_access_key_testing
get:
  path: drone/cust-testing-newsletter
  name: aws_access_key
---
kind: secret
name: aws_access_key_secret_testing
get:
  path: drone/cust-testing-newsletter
  name: aws_access_key_secret

---
kind: secret
name: aws_access_key_production
get:
  path: drone/cust-production-newsletter
  name: aws_access_key
---
kind: secret
name: aws_access_key_secret_production
get:
  path: drone/cust-production-newsletter
  name: aws_access_key_secret
