version: "3.3"
services:
  frontend:
    build:
      context: .
    image: ses-dasboard
    ports:
      - "4200:4200"
    env_file:
      - .env
    command: npm run serve
    volumes:
    - ./environment.local.ts:/SES-bounce-notification/src/environments/environment.ts
  backend:
    image: ses-dasboard
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm start
